FUNCTION compileFile RETURNS LOGICAL (INPUT srcFile AS CHARACTER, INPUT outDir AS CHARACTER):
	COMPILE VALUE(srcFile)
	SAVE INTO VALUE(outDir)
	GENERATE-MD5.

	RETURN YES.
END.

DEFINE VAR file AS CHARACTER NO-UNDO.
DEFINE VAR outputDir AS CHARACTER NO-UNDO.
DEFINE VAR sourceDir AS CHARACTER NO-UNDO.

sourceDir = ENTRY(1, SESSION:PARAMETER).
file = ENTRY(2, SESSION:PARAMETER).
outputDir = ENTRY(3, SESSION:PARAMETER).

PROPATH = sourceDir + "," + PROPATH.

compileFile(file, outputDir).
QUIT.
