&IF defined(TEST_LIST)=0 &THEN
&GLOBAL-DEFINE TEST_LIST "{1}"
&GLOBAL-DEFINE TEST_COUNT 1
&ELSE
&GLOBAL-DEFINE TEST_LIST {&TEST_LIST}, "{1}"
&GLOBAL-DEFINE TEST_COUNT (1 + {&TEST_COUNT})
&ENDIF
FUNCTION {1} RETURNS LOGICAL ():